# Secret scanning configuration
# These are public OAuth client credentials for desktop/CLI applications
# following the OAuth 2.0 "installed application" pattern.
# See: https://developers.google.com/identity/protocols/oauth2#installed

paths-ignore:
  - 'internal/oauth/defaults.go'  # Contains public OAuth client credentials for desktop apps
